<?php

// Flat icons
function saasland_flaticons() {
    return [
        'flaticon-target' => 'Target',
        'flaticon-lightbulb' => 'Light Bulb',
        'flaticon-mortarboard' => 'Mortar Board',
    ];
}

function saasland_include_flaticons() {
    return array_keys(saasland_flaticons());
}


/**
 * Simple Line Icon Library
 * @return array
 */
function saasland_simple_line_icons() {
    $simple_line_icons = [
        'icon-user',
        'icon-people',
        'icon-user-female',
        'icon-user-follow',
        'icon-user-following',
        'icon-user-unfollow',
        'icon-login',
        'icon-logout',
        'icon-emotsmile',
        'icon-phone',
        'icon-call-end',
        'icon-call-in',
        'icon-call-out',
        'icon-map',
        'icon-location-pin',
        'icon-direction',
        'icon-directions',
        'icon-compass',
        'icon-layers',
        'icon-menu',
        'icon-list',
        'icon-options-vertica',
        'icon-options',
        'icon-arrow-down',
        'icon-arrow-left',
        'icon-arrow-right',
        'icon-arrow-up',
        'icon-arrow-up-circle',
        'icon-arrow-left-circ',
        'icon-arrow-right-cir',
        'icon-arrow-down-circ',
        'icon-check',
        'icon-clock',
        'icon-plus',
        'icon-minus',
        'icon-close',
        'icon-event',
        'icon-exclamation',
        'icon-organization',
        'icon-trophy',
        'icon-screen-smartpho',
        'icon-screen-desktop',
        'icon-plane',
        'icon-notebook',
        'icon-mustache',
        'icon-mouse',
        'icon-magnet',
        'icon-energy',
        'icon-disc',
        'icon-cursor',
        'icon-cursor-move',
        'icon-crop',
        'icon-chemistry',
        'icon-speedometer',
        'icon-shield',
        'icon-screen-tablet',
        'icon-magic-wand',
        'icon-hourglass',
        'icon-graduation',
        'icon-ghost',
        'icon-game-controller',
        'icon-fire',
        'icon-eyeglass',
        'icon-envelope-open',
        'icon-envelope-letter',
        'icon-bell',
        'icon-badge',
        'icon-anchor',
        'icon-wallet',
        'icon-vector',
        'icon-speech',
        'icon-puzzle',
        'icon-printer',
        'icon-present',
        'icon-playlist',
        'icon-pin',
        'icon-picture',
        'icon-handbag',
        'icon-globe-alt',
        'icon-globe',
        'icon-folder-alt',
        'icon-folder',
        'icon-film',
        'icon-feed',
        'icon-drop',
        'icon-drawer',
        'icon-docs',
        'icon-doc',
        'icon-diamond',
        'icon-cup',
        'icon-calculator',
        'icon-bubbles',
        'icon-briefcase',
        'icon-book-open',
        'icon-basket-loaded',
        'icon-basket',
        'icon-bag',
        'icon-action-undo',
        'icon-action-redo',
        'icon-wrench',
        'icon-umbrella',
        'icon-trash',
        'icon-tag',
        'icon-support',
        'icon-frame',
        'icon-size-fullscreen',
        'icon-size-actual',
        'icon-shuffle',
        'icon-share-alt',
        'icon-share',
        'icon-rocket',
        'icon-question',
        'icon-pie-chart',
        'icon-pencil',
        'icon-note',
        'icon-loop',
        'icon-home',
        'icon-grid',
        'icon-graph',
        'icon-microphone',
        'icon-music-tone-alt',
        'icon-music-tone',
        'icon-earphones-alt',
        'icon-earphones',
        'icon-equalizer',
        'icon-like',
        'icon-dislike',
        'icon-control-start',
        'icon-control-rewind',
        'icon-control-play',
        'icon-control-pause',
        'icon-control-forward',
        'icon-control-end',
        'icon-volume-1',
        'icon-volume-2',
        'icon-volume-off',
        'icon-calendar',
        'icon-bulb',
        'icon-chart',
        'icon-ban',
        'icon-bubble',
        'icon-camrecorder',
        'icon-camera',
        'icon-cloud-download',
        'icon-cloud-upload',
        'icon-envelope',
        'icon-eye',
        'icon-flag',
        'icon-heart',
        'icon-info',
        'icon-key',
        'icon-link',
        'icon-lock',
        'icon-lock-open',
        'icon-magnifier',
        'icon-magnifier-add',
        'icon-magnifier-remove',
        'icon-paper-clip',
        'icon-paper-plane',
        'icon-power',
        'icon-refresh',
        'icon-reload',
        'icon-settings',
        'icon-star',
        'icon-symbol-female',
        'icon-symbol-male',
        'icon-target',
        'icon-credit-card',
        'icon-paypal',
        'icon-social-tumblr',
        'icon-social-twitter',
        'icon-social-facebook',
        'icon-social-instagram',
        'icon-social-linkedin',
        'icon-social-pinterest',
        'icon-social-github',
        'icon-social-google',
        'icon-social-reddit',
        'icon-social-skype',
        'icon-social-dribbble',
        'icon-social-behance',
        'icon-social-foursqare',
        'icon-social-soundclou',
        'icon-social-spotify',
        'icon-social-stumbleup',
        'icon-social-youtube',
        'icon-social-dropbox',
        'icon-social-vkontakte',
    ];
    return saasland_icon_array($simple_line_icons);
}

function saasland_include_simple_line_icons() {
    return array_keys(saasland_simple_line_icons());
}


/**
 * Elegant Icons
 */
function saasland_elegant_icons() {
    $et_icons = 'arrow_up, arrow_down, arrow_left, arrow_right, arrow_left-up, arrow_right-up, arrow_right-down, arrow_left-down, arrow-up-down, arrow_up-down_alt, arrow_left-right_alt, arrow_left-right, arrow_expand_alt2, arrow_expand_alt, arrow_condense, arrow_expand, arrow_move, arrow_carrot-up, arrow_carrot-down, arrow_carrot-left, arrow_carrot-right, arrow_carrot-2up, arrow_carrot-2down, arrow_carrot-2left, arrow_carrot-2right, arrow_carrot-up_alt2, arrow_carrot-down_alt2, arrow_carrot-left_alt2, arrow_carrot-right_alt2, arrow_carrot-2up_alt2, arrow_carrot-2down_alt2, arrow_carrot-2left_alt2, arrow_carrot-2right_alt2, arrow_triangle-up, arrow_triangle-down, arrow_triangle-left, arrow_triangle-right, arrow_triangle-up_alt2, arrow_triangle-down_alt2, arrow_triangle-left_alt2, arrow_triangle-right_alt2, arrow_back, icon_minus-06, icon_plus, icon_close, icon_check, icon_minus_alt2, icon_plus_alt2, icon_close_alt2, icon_check_alt2, icon_zoom-out_alt, icon_zoom-in_alt, icon_search, icon_box-empty, icon_box-selected, icon_minus-box, icon_plus-box, icon_box-checked, icon_circle-empty, icon_circle-slelected, icon_stop_alt2, icon_stop, icon_pause_alt2, icon_pause, icon_menu, icon_menu-square_alt2, icon_menu-circle_alt2, icon_ul, icon_ol, icon_adjust-horiz, icon_adjust-vert, icon_document_alt, icon_documents_alt, icon_pencil, icon_pencil-edit_alt, icon_pencil-edit, icon_folder-alt, icon_folder-open_alt, icon_folder-add_alt, icon_info_alt, icon_error-oct_alt, icon_error-circle_alt, icon_error-triangle_alt, icon_question_alt2, icon_question, icon_comment_alt, icon_chat_alt, icon_vol-mute_alt, icon_volume-low_alt, icon_volume-high_alt, icon_quotations, icon_quotations_alt2, icon_clock_alt, icon_lock_alt, icon_lock-open_alt, icon_key_alt, icon_cloud_alt, icon_cloud-upload_alt, icon_cloud-download_alt, icon_image, icon_images, icon_lightbulb_alt, icon_gift_alt, icon_house_alt, icon_genius, icon_mobile, icon_tablet, icon_laptop, icon_desktop, icon_camera_alt, icon_mail_alt, icon_cone_alt, icon_ribbon_alt, icon_bag_alt, icon_creditcard, icon_cart_alt, icon_paperclip, icon_tag_alt, icon_tags_alt, icon_trash_alt, icon_cursor_alt, icon_mic_alt, icon_compass_alt, icon_pin_alt, icon_pushpin_alt, icon_map_alt, icon_drawer_alt, icon_toolbox_alt, icon_book_alt, icon_calendar, icon_film, icon_table, icon_contacts_alt, icon_headphones, icon_lifesaver, icon_piechart, icon_refresh, icon_link_alt, icon_link, icon_loading, icon_blocked, icon_archive_alt, icon_heart_alt, icon_star_alt, icon_star-half_alt, icon_star, icon_star-half, icon_tools, icon_tool, icon_cog, icon_cogs, arrow_up_alt, arrow_down_alt, arrow_left_alt, arrow_right_alt, arrow_left-up_alt, arrow_right-up_alt, arrow_right-down_alt, arrow_left-down_alt, arrow_condense_alt, arrow_expand_alt3, arrow_carrot_up_alt, arrow_carrot-down_alt, arrow_carrot-left_alt, arrow_carrot-right_alt, arrow_carrot-2up_alt, arrow_carrot-2dwnn_alt, arrow_carrot-2left_alt, arrow_carrot-2right_alt, arrow_triangle-up_alt, arrow_triangle-down_alt, arrow_triangle-left_alt, arrow_triangle-right_alt, icon_minus_alt, icon_plus_alt, icon_close_alt, icon_check_alt, icon_zoom-out, icon_zoom-in, icon_stop_alt, icon_menu-square_alt, icon_menu-circle_alt, icon_document, icon_documents, icon_pencil_alt, icon_folder, icon_folder-open, icon_folder-add, icon_folder_upload, icon_folder_download, icon_info, icon_error-circle, icon_error-oct, icon_error-triangle, icon_question_alt, icon_comment, icon_chat, icon_vol-mute, icon_volume-low, icon_volume-high, icon_quotations_alt, icon_clock, icon_lock, icon_lock-open, icon_key, icon_cloud, icon_cloud-upload, icon_cloud-download, icon_lightbulb, icon_gift, icon_house, icon_camera, icon_mail, icon_cone, icon_ribbon, icon_bag, icon_cart, icon_tag, icon_tags, icon_trash, icon_cursor, icon_mic, icon_compass, icon_pin, icon_pushpin, icon_map, icon_drawer, icon_toolbox, icon_book, icon_contacts, icon_archive, icon_heart, icon_profile, icon_group, icon_grid-2x2, icon_grid-3x3, icon_music, icon_pause_alt, icon_phone, icon_upload, icon_download, social_facebook, social_twitter, social_pinterest, social_googleplus, social_tumblr, social_tumbleupon, social_wordpress, social_instagram, social_dribbble, social_vimeo, social_linkedin, social_rss, social_deviantart, social_share, social_myspace, social_skype, social_youtube, social_picassa, social_googledrive, social_flickr, social_blogger, social_spotify, social_delicious, social_facebook_circle, social_twitter_circle, social_pinterest_circle, social_googleplus_circle, social_tumblr_circle, social_stumbleupon_circle, social_wordpress_circle, social_instagram_circle, social_dribbble_circle, social_vimeo_circle, social_linkedin_circle, social_rss_circle, social_deviantart_circle, social_share_circle, social_myspace_circle, social_skype_circle, social_youtube_circle, social_picassa_circle, social_googledrive_alt2, social_flickr_circle, social_blogger_circle, social_spotify_circle, social_delicious_circle, social_facebook_square, social_twitter_square, social_pinterest_square, social_googleplus_square, social_tumblr_square, social_stumbleupon_square, social_wordpress_square, social_instagram_square, social_dribbble_square, social_vimeo_square, social_linkedin_square, social_rss_square, social_deviantart_square, social_share_square, social_myspace_square, social_skype_square, social_youtube_square, social_picassa_square, social_googledrive_square, social_flickr_square, social_blogger_square, social_spotify_square, social_delicious_square, icon_printer, icon_calulator, icon_building, icon_floppy, icon_drive, icon_search-2, icon_id, icon_id-2, icon_puzzle, icon_like, icon_dislike, icon_mug, icon_currency, icon_wallet, icon_pens, icon_easel, icon_flowchart, icon_datareport, icon_briefcase, icon_shield, icon_percent, icon_globe, icon_globe-2, icon_target, icon_hourglass, icon_balance, icon_rook, icon_printer-alt, icon_calculator_alt, icon_building_alt, icon_floppy_alt, icon_drive_alt, icon_search_alt, icon_id_alt, icon_id-2_alt, icon_puzzle_alt, icon_like_alt, icon_dislike_alt, icon_mug_alt, icon_currency_alt, icon_wallet_alt, icon_pens_alt, icon_easel_alt, icon_flowchart_alt, icon_datareport_alt, icon_briefcase_alt, icon_shield_alt, icon_percent_alt, icon_globe_alt, icon_clipboard';
    $et_icons = explode( ', ', $et_icons);
    return saasland_icon_array($et_icons, '', '_');
}

function saasland_include_elegant_icons() {
    return array_keys(saasland_elegant_icons());
}


/**
 * Themify Icon Library
 * @return array
 */
function saasland_themify_icons() {
    return [
        'ti-wand' => esc_html__( 'Wand', 'saasland-core'),
        'ti-volume' => esc_html__( 'Volume', 'saasland-core'),
        'ti-user' => esc_html__( 'User', 'saasland-core'),
        'ti-unlock' => esc_html__( 'Unlock', 'saasland-core'),
        'ti-unlink' => esc_html__( 'Unlink', 'saasland-core'),
        'ti-trash' => esc_html__( 'Trash', 'saasland-core'),
        'ti-thought' => esc_html__( 'Thought', 'saasland-core'),
        'ti-target' => esc_html__( 'Target', 'saasland-core'),
        'ti-tag' => esc_html__( 'Tag', 'saasland-core'),
        'ti-tablet' => esc_html__( 'Tablet', 'saasland-core'),
        'ti-star' => esc_html__( 'Star', 'saasland-core'),
        'ti-spray' => esc_html__( 'Spray', 'saasland-core'),
        'ti-shopping-cart-full' => esc_html__( 'Shopping Cart Full', 'saasland-core'),
        'ti-shopping-cart' => esc_html__( 'Shopping Cart', 'saasland-core'),
        'ti-settings' => esc_html__( 'Settings', 'saasland-core'),
        'ti-search' => esc_html__( 'Search', 'saasland-core'),
        'ti-zoom-in' => esc_html__( 'Zoom In', 'saasland-core'),
        'ti-zoom-out' => esc_html__( 'Zoom Out', 'saasland-core'),
        'ti-cut' => esc_html__( 'Cut', 'saasland-core'),
        'ti-ruler' => esc_html__( 'Ruler', 'saasland-core'),
        'ti-ruler-pencil' => esc_html__( 'Ruler Pencil', 'saasland-core'),
        'ti-ruler-alt' => esc_html__( 'Ruler alt', 'saasland-core'),
        'ti-bookmark' => esc_html__( 'Bookmark', 'saasland-core'),
        'ti-bookmark-alt' => esc_html__( 'Bookmark Alt', 'saasland-core'),
        'ti-reload' => esc_html__( 'Reload', 'saasland-core'),
        'ti-plus' => esc_html__( 'Plus', 'saasland-core'),
        'ti-pin' => esc_html__( 'Pin', 'saasland-core'),
        'ti-pencil' => esc_html__( 'Pencil', 'saasland-core'),
        'ti-pencil-alt' => esc_html__( 'Pencil Alt', 'saasland-core'),
        'ti-paint-roller' => esc_html__( 'Paint Roller', 'saasland-core'),
        'ti-paint-bucket' => esc_html__( 'Paint Bucket', 'saasland-core'),
        'ti-na' => esc_html__( 'Na', 'saasland-core'),
        'ti-mobile' => esc_html__( 'Mobile', 'saasland-core'),
        'ti-minus' => esc_html__( 'Minus', 'saasland-core'),
        'ti-medall' => esc_html__( 'Medall', 'saasland-core'),
        'ti-medall-alt' => esc_html__( 'Medall Alt', 'saasland-core'),
        'ti-marker' => esc_html__( 'Marker', 'saasland-core'),
        'ti-marker-alt' => esc_html__( 'Marker Alt', 'saasland-core'),
        'ti-arrow-up' => esc_html__( 'Arrow Up', 'saasland-core'),
        'ti-arrow-right' => esc_html__( 'Arrow Right', 'saasland-core'),
        'ti-arrow-left' => esc_html__( 'Arrow Left', 'saasland-core'),
        'ti-arrow-down' => esc_html__( 'Arrow Down', 'saasland-core'),
        'ti-lock' => esc_html__( 'Lock', 'saasland-core'),
        'ti-location-arrow' => esc_html__( 'Location Arrow', 'saasland-core'),
        'ti-link' => esc_html__( 'Link', 'saasland-core'),
        'ti-layout' => esc_html__( 'Layout', 'saasland-core'),
        'ti-layers' => esc_html__( 'Layers', 'saasland-core'),
        'ti-layers-alt' => esc_html__( 'Layers Alt', 'saasland-core'),
        'ti-key' => esc_html__( 'Key', 'saasland-core'),
        'ti-import' => esc_html__( 'Import', 'saasland-core'),
        'ti-image' => esc_html__( 'Image', 'saasland-core'),
        'ti-heart' => esc_html__( 'Heart', 'saasland-core'),
        'ti-heart-broken' => esc_html__( 'Heart Broken', 'saasland-core'),
        'ti-hand-stop' => esc_html__( 'Hand Stop', 'saasland-core'),
        'ti-hand-open' => esc_html__( 'Hand Open', 'saasland-core'),
        'ti-hand-drag' => esc_html__( 'Hand Drag', 'saasland-core'),
        'ti-folder' => esc_html__( 'Folder', 'saasland-core'),
        'ti-flag' => esc_html__( 'Flag', 'saasland-core'),
        'ti-flag-alt' => esc_html__( 'Flag Alt', 'saasland-core'),
        'ti-flag-alt-2' => esc_html__( 'Flag Alt 2', 'saasland-core'),
        'ti-eye' => esc_html__( 'Eye', 'saasland-core'),
        'ti-export' => esc_html__( 'Export', 'saasland-core'),
        'ti-exchange-vertical' => esc_html__( 'Exchange Vertical', 'saasland-core'),
        'ti-desktop' => esc_html__( 'Desktop', 'saasland-core'),
        'ti-cup' => esc_html__( 'Cup', 'saasland-core'),
        'ti-crown' => esc_html__( 'Crown', 'saasland-core'),
        'ti-comments' => esc_html__( 'Comments', 'saasland-core'),
        'ti-comment' => esc_html__( 'Comment', 'saasland-core'),
        'ti-comment-alt' => esc_html__( 'Comment Alt', 'saasland-core'),
        'ti-close' => esc_html__( 'Close', 'saasland-core'),
        'ti-clip' => esc_html__( 'Clip', 'saasland-core'),
        'ti-angle-up' => esc_html__( 'Angle Up', 'saasland-core'),
        'ti-angle-right' => esc_html__( 'Angle Right', 'saasland-core'),
        'ti-angle-left' => esc_html__( 'Angle Left', 'saasland-core'),
        'ti-angle-down' => esc_html__( 'Angle Down', 'saasland-core'),
        'ti-check' => esc_html__( 'Check', 'saasland-core'),
        'ti-check-box' => esc_html__( 'Check Box', 'saasland-core'),
        'ti-camera' => esc_html__( 'Camera', 'saasland-core'),
        'ti-announcement' => esc_html__( 'Announcement', 'saasland-core'),
        'ti-brush' => esc_html__( 'Brush', 'saasland-core'),
        'ti-briefcase' => esc_html__( 'Briefcase', 'saasland-core'),
        'ti-bolt' => esc_html__( 'Bolt', 'saasland-core'),
        'ti-bolt-alt' => esc_html__( 'Bolt Alt', 'saasland-core'),
        'ti-blackboard' => esc_html__( 'Blackboard', 'saasland-core'),
        'ti-bag' => esc_html__( 'Bag', 'saasland-core'),
        'ti-move' => esc_html__( 'Move', 'saasland-core'),
        'ti-arrows-vertical' => esc_html__( 'Arrows Vertical', 'saasland-core'),
        'ti-arrows-horizontal' => esc_html__( 'Arrows Horizontal', 'saasland-core'),
        'ti-fullscreen' => esc_html__( 'Fullscreen', 'saasland-core'),
        'ti-arrow-top-right' => esc_html__( 'Arrow Top Right', 'saasland-core'),
        'ti-arrow-top-left' => esc_html__( 'Arrow Top Left', 'saasland-core'),
        'ti-arrow-circle-up' => esc_html__( 'Arrow Circle Up', 'saasland-core'),
        'ti-arrow-circle-right' => esc_html__( 'Arrow Circle Right', 'saasland-core'),
        'ti-arrow-circle-left' => esc_html__( 'Arrow Circle Left', 'saasland-core'),
        'ti-arrow-circle-down' => esc_html__( 'Arrow Circle Down', 'saasland-core'),
        'ti-angle-double-up' => esc_html__( 'Angle Double Up', 'saasland-core'),
        'ti-angle-double-right' => esc_html__( 'Angle Double Right', 'saasland-core'),
        'ti-angle-double-left' => esc_html__( 'Angle Double Left', 'saasland-core'),
        'ti-angle-double-down' => esc_html__( 'Angle Double Down', 'saasland-core'),
        'ti-zip' => esc_html__( 'Zip', 'saasland-core'),
        'ti-world' => esc_html__( 'World', 'saasland-core'),
        'ti-wheelchair' => esc_html__( 'Wheelchair', 'saasland-core'),
        'ti-view-list' => esc_html__( 'View List', 'saasland-core'),
        'ti-view-list-alt' => esc_html__( 'View List Alt', 'saasland-core'),
        'ti-view-grid' => esc_html__( 'View Grid', 'saasland-core'),
        'ti-uppercase' => esc_html__( 'Uppercase', 'saasland-core'),
        'ti-upload' => esc_html__( 'Upload', 'saasland-core'),
        'ti-underline' => esc_html__( 'Underline', 'saasland-core'),
        'ti-truck' => esc_html__( 'Truck', 'saasland-core'),
        'ti-timer' => esc_html__( 'Timer', 'saasland-core'),
        'ti-ticket' => esc_html__( 'Ticket', 'saasland-core'),
        'ti-thumb-up' => esc_html__( 'Thumb Up', 'saasland-core'),
        'ti-thumb-down' => esc_html__( 'Thumb Down', 'saasland-core'),
        'ti-text' => esc_html__( 'Text', 'saasland-core'),
        'ti-stats-up' => esc_html__( 'Stats Up', 'saasland-core'),
        'ti-stats-down' => esc_html__( 'Stats Down', 'saasland-core'),
        'ti-split-v' => esc_html__( 'Split V', 'saasland-core'),
        'ti-split-h' => esc_html__( 'Split-h', 'saasland-core'),
        'ti-smallcap' => esc_html__( 'Smallcap', 'saasland-core'),
        'ti-shine' => esc_html__( 'Shine', 'saasland-core'),
        'ti-shift-right' => esc_html__( 'Shift Right', 'saasland-core'),
        'ti-shift-left' => esc_html__( 'Shift Left', 'saasland-core'),
        'ti-shield' => esc_html__( 'Shield', 'saasland-core'),
        'ti-notepad' => esc_html__( 'Notepad', 'saasland-core'),
        'ti-server' => esc_html__( 'Server', 'saasland-core'),
        'ti-quote-right' => esc_html__( 'Quote Right', 'saasland-core'),
        'ti-quote-left' => esc_html__( 'Quote Left', 'saasland-core'),
        'ti-pulse' => esc_html__( 'Pulse', 'saasland-core'),
        'ti-printer' => esc_html__( 'Printer', 'saasland-core'),
        'ti-power-off' => esc_html__( 'Power Off', 'saasland-core'),
        'ti-plug' => esc_html__( 'Plug', 'saasland-core'),
        'ti-pie-chart' => esc_html__( 'Pie Chart', 'saasland-core'),
        'ti-paragraph' => esc_html__( 'Paragraph', 'saasland-core'),
        'ti-panel' => esc_html__( 'Panel', 'saasland-core'),
        'ti-package' => esc_html__( 'Package', 'saasland-core'),
        'ti-music' => esc_html__( 'Music', 'saasland-core'),
        'ti-music-alt' => esc_html__( 'Music Alt', 'saasland-core'),
        'ti-mouse' => esc_html__( 'Mouse', 'saasland-core'),
        'ti-mouse-alt' => esc_html__( 'Mouse Alt', 'saasland-core'),
        'ti-money' => esc_html__( 'Money', 'saasland-core'),
        'ti-microphone' => esc_html__( 'Microphone', 'saasland-core'),
        'ti-menu' => esc_html__( 'Menu', 'saasland-core'),
        'ti-menu-alt' => esc_html__( 'Menu Alt', 'saasland-core'),
        'ti-map' => esc_html__( 'Map', 'saasland-core'),
        'ti-map-alt' => esc_html__( 'Map Alt', 'saasland-core'),
        'ti-loop' => esc_html__( 'Loop', 'saasland-core'),
        'ti-location-pin' => esc_html__( 'Location Pin', 'saasland-core'),
        'ti-list' => esc_html__( 'List', 'saasland-core'),
        'ti-light-bulb' => esc_html__( 'Light Bulb', 'saasland-core'),
        'ti-Italic' => esc_html__( 'Italic', 'saasland-core'),
        'ti-info' => esc_html__( 'Info', 'saasland-core'),
        'ti-infinite' => esc_html__( 'Infinite', 'saasland-core'),
        'ti-id-badge' => esc_html__( 'Badge', 'saasland-core'),
        'ti-hummer' => esc_html__( 'Hummer', 'saasland-core'),
        'ti-home' => esc_html__( 'Home', 'saasland-core'),
        'ti-help' => esc_html__( 'Help', 'saasland-core'),
        'ti-headphone' => esc_html__( 'Headphone', 'saasland-core'),
        'ti-harddrives' => esc_html__( 'Harddrives', 'saasland-core'),
        'ti-harddrive' => esc_html__( 'Harddrive', 'saasland-core'),
        'ti-gift' => esc_html__( 'Gift', 'saasland-core'),
        'ti-game' => esc_html__( 'Game', 'saasland-core'),
        'ti-filter' => esc_html__( 'Filter', 'saasland-core'),
        'ti-files' => esc_html__( 'Files', 'saasland-core'),
        'ti-file' => esc_html__( 'File', 'saasland-core'),
        'ti-eraser' => esc_html__( 'Eraser', 'saasland-core'),
        'ti-envelope' => esc_html__( 'Envelope', 'saasland-core'),
        'ti-download' => esc_html__( 'Download', 'saasland-core'),
        'ti-direction' => esc_html__( 'Direction', 'saasland-core'),
        'ti-direction-alt' => esc_html__( 'Direction Alt', 'saasland-core'),
        'ti-dashboard' => esc_html__( 'Dashboard', 'saasland-core'),
        'ti-control-stop' => esc_html__( 'Control Stop', 'saasland-core'),
        'ti-control-shuffle' => esc_html__( 'Control Shuffle', 'saasland-core'),
        'ti-control-play' => esc_html__( 'Control Play', 'saasland-core'),
        'ti-control-pause' => esc_html__( 'Control Pause', 'saasland-core'),
        'ti-control-forward' => esc_html__( 'Control Forward', 'saasland-core'),
        'ti-control-backward' => esc_html__( 'Control Backward', 'saasland-core'),
        'ti-cloud' => esc_html__( 'Cloud', 'saasland-core'),
        'ti-cloud-up' => esc_html__( 'Cloud-up', 'saasland-core'),
        'ti-cloud-down' => esc_html__( 'Cloud Down', 'saasland-core'),
        'ti-clipboard' => esc_html__( 'Clipboard', 'saasland-core'),
        'ti-car' => esc_html__( 'Car', 'saasland-core'),
        'ti-calendar' => esc_html__( 'Calendar', 'saasland-core'),
        'ti-book' => esc_html__( 'Book', 'saasland-core'),
        'ti-bell' => esc_html__( 'Bell', 'saasland-core'),
        'ti-basketball' => esc_html__( 'Basketball', 'saasland-core'),
        'ti-bar-chart' => esc_html__( 'Bar Chart', 'saasland-core'),
        'ti-bar-chart-alt' => esc_html__( 'Bar Chart Alt', 'saasland-core'),
        'ti-back-right' => esc_html__( 'Back Right', 'saasland-core'),
        'ti-back-left' => esc_html__( 'Back Left', 'saasland-core'),
        'ti-arrows-corner' => esc_html__( 'Arrows Corner', 'saasland-core'),
        'ti-archive' => esc_html__( 'Archive', 'saasland-core'),
        'ti-anchor' => esc_html__( 'Anchor', 'saasland-core'),
        'ti-align-right' => esc_html__( 'Align Right', 'saasland-core'),
        'ti-align-left' => esc_html__( 'Align Left', 'saasland-core'),
        'ti-align-justify' => esc_html__( 'Align Justify', 'saasland-core'),
        'ti-align-center' => esc_html__( 'Align Center', 'saasland-core'),
        'ti-alert' => esc_html__( 'Alert', 'saasland-core'),
        'ti-alarm-clock' => esc_html__( 'Alarm Clock', 'saasland-core'),
        'ti-agenda' => esc_html__( 'Agenda', 'saasland-core'),
        'ti-write' => esc_html__( 'Write', 'saasland-core'),
        'ti-window' => esc_html__( 'Window', 'saasland-core'),
        'ti-widgetized' => esc_html__( 'Widgetized', 'saasland-core'),
        'ti-widget' => esc_html__( 'Widget', 'saasland-core'),
        'ti-widget-alt' => esc_html__( 'Widget Alt', 'saasland-core'),
        'ti-wallet' => esc_html__( 'Wallet', 'saasland-core'),
        'ti-video-clapper' => esc_html__( 'Video Clapper', 'saasland-core'),
        'ti-video-camera' => esc_html__( 'Video Camera', 'saasland-core'),
        'ti-vector' => esc_html__( 'Vector', 'saasland-core'),
        'ti-themify-logo' => esc_html__( 'Themify Logo', 'saasland-core'),
        'ti-themify-favicon' => esc_html__( 'Themify Favicon', 'saasland-core'),
        'ti-themify-favicon-alt' => esc_html__( 'Themify Favicon Alt', 'saasland-core'),
        'ti-support' => esc_html__( 'Support', 'saasland-core'),
        'ti-stamp' => esc_html__( 'Stamp', 'saasland-core'),
        'ti-split-v-alt' => esc_html__( 'Split V Alt', 'saasland-core'),
        'ti-slice' => esc_html__( 'Slice', 'saasland-core'),
        'ti-shortcode' => esc_html__( 'Shortcode', 'saasland-core'),
        'ti-shift-right-alt' => esc_html__( 'Shift Right Alt', 'saasland-core'),
        'ti-shift-left-alt' => esc_html__( 'Shift Left Alt', 'saasland-core'),
        'ti-ruler-alt-2' => esc_html__( 'Ruler Alt 2', 'saasland-core'),
        'ti-receipt' => esc_html__( 'Receipt', 'saasland-core'),
        'ti-pin2' => esc_html__( 'Pin2', 'saasland-core'),
        'ti-pin-alt' => esc_html__( 'Pin Alt', 'saasland-core'),
        'ti-pencil-alt2' => esc_html__( 'Pencil Alt2', 'saasland-core'),
        'ti-palette' => esc_html__( 'Palette', 'saasland-core'),
        'ti-more' => esc_html__( 'More', 'saasland-core'),
        'ti-more-alt' => esc_html__( 'More Alt', 'saasland-core'),
        'ti-microphone-alt' => esc_html__( 'Microphone Alt', 'saasland-core'),
        'ti-magnet' => esc_html__( 'Magnet', 'saasland-core'),
        'ti-line-double' => esc_html__( 'Line Double', 'saasland-core'),
        'ti-line-dotted' => esc_html__( 'Line Dotted', 'saasland-core'),
        'ti-line-dashed' => esc_html__( 'Line Dashed', 'saasland-core'),
        'ti-layout-width-full' => esc_html__( 'Layout Width Full', 'saasland-core'),
        'ti-layout-width-default' => esc_html__( 'Layout Width Default', 'saasland-core'),
        'ti-layout-width-default-alt' => esc_html__( 'Layout Width Default Alt', 'saasland-core'),
        'ti-layout-tab' => esc_html__( 'Layout Tab', 'saasland-core'),
        'ti-layout-tab-window' => esc_html__( 'Layout Tab Window', 'saasland-core'),
        'ti-layout-tab-v' => esc_html__( 'Layout Tab V', 'saasland-core'),
        'ti-layout-tab-min' => esc_html__( 'Layout Tab Min', 'saasland-core'),
        'ti-layout-slider' => esc_html__( 'Layout Slider', 'saasland-core'),
        'ti-layout-slider-alt' => esc_html__( 'Layout Slider Alt', 'saasland-core'),
        'ti-layout-sidebar-right' => esc_html__( 'Layout Sidebar Right', 'saasland-core'),
        'ti-layout-sidebar-none' => esc_html__( 'Layout Sidebar None', 'saasland-core'),
        'ti-layout-sidebar-left' => esc_html__( 'Layout Sidebar Left', 'saasland-core'),
        'ti-layout-placeholder' => esc_html__( 'Layout Placeholder', 'saasland-core'),
        'ti-layout-menu' => esc_html__( 'Layout Menu', 'saasland-core'),
        'ti-layout-menu-v' => esc_html__( 'layout Menu V', 'saasland-core'),
        'ti-layout-menu-separated' => esc_html__( 'Layout Menu Separated', 'saasland-core'),
        'ti-layout-menu-full' => esc_html__( 'Layout Menu Full', 'saasland-core'),
        'ti-layout-media-right-alt' => esc_html__( 'Layout Media Right Alt', 'saasland-core'),
        'ti-layout-media-right' => esc_html__( 'Layout Media Right', 'saasland-core'),
        'ti-layout-media-overlay' => esc_html__( 'Layout Media Overlay', 'saasland-core'),
        'ti-layout-media-overlay-alt' => esc_html__( 'Layout Media Overlay Alt', 'saasland-core'),
        'ti-layout-media-overlay-alt-2' => esc_html__( 'Layout Media Overlay Alt 2', 'saasland-core'),
        'ti-layout-media-left-alt' => esc_html__( 'Layout Media Left Alt', 'saasland-core'),
        'ti-layout-media-left' => esc_html__( 'Layout Media Left', 'saasland-core'),
        'ti-layout-media-center-alt' => esc_html__( 'Layout Media Center Alt', 'saasland-core'),
        'ti-layout-media-center' => esc_html__( 'Layout Media Center', 'saasland-core'),
        'ti-layout-list-thumb' => esc_html__( 'Layout List Thumb', 'saasland-core'),
        'ti-layout-list-thumb-alt' => esc_html__( 'Layout List Thumb Alt', 'saasland-core'),
        'ti-layout-list-post' => esc_html__( 'Layout List Post', 'saasland-core'),
        'ti-layout-list-large-image' => esc_html__( 'Layout List Large Image', 'saasland-core'),
        'ti-layout-line-solid' => esc_html__( 'Layout Line Solid', 'saasland-core'),
        'ti-layout-grid4' => esc_html__( 'Layout Grid4', 'saasland-core'),
        'ti-layout-grid3' => esc_html__( 'Layout Grid3', 'saasland-core'),
        'ti-layout-grid2' => esc_html__( 'Layout Grid2', 'saasland-core'),
        'ti-layout-grid2-thumb' => esc_html__( 'Layout Grid2 Thumb', 'saasland-core'),
        'ti-layout-cta-right' => esc_html__( 'Layout Cta Right', 'saasland-core'),
        'ti-layout-cta-left' => esc_html__( 'Layout Cta Left', 'saasland-core'),
        'ti-layout-cta-center' => esc_html__( 'Layout Cta Center', 'saasland-core'),
        'ti-layout-cta-btn-right' => esc_html__( 'Layout Cta Btn Right', 'saasland-core'),
        'ti-layout-cta-btn-left' => esc_html__( 'Layout Cta Btn Left', 'saasland-core'),
        'ti-layout-column4' => esc_html__( 'Layout Column4', 'saasland-core'),
        'ti-layout-column3' => esc_html__( 'Layout Column3', 'saasland-core'),
        'ti-layout-column2' => esc_html__( 'Layout Column2', 'saasland-core'),
        'ti-layout-accordion-separated' => esc_html__( 'Layout Accordion Separated', 'saasland-core'),
        'ti-layout-accordion-merged' => esc_html__( 'Layout Accordion Merged', 'saasland-core'),
        'ti-layout-accordion-list' => esc_html__( 'Layout Accordion List', 'saasland-core'),
        'ti-ink-pen' => esc_html__( 'Ink Pen', 'saasland-core'),
        'ti-info-alt' => esc_html__( 'Info Alt', 'saasland-core'),
        'ti-help-alt' => esc_html__( 'Help Alt', 'saasland-core'),
        'ti-headphone-alt' => esc_html__( 'Headphone Alt', 'saasland-core'),
        'ti-hand-point-up' => esc_html__( 'Hand Point Up', 'saasland-core'),
        'ti-hand-point-right' => esc_html__( 'Hand Point Right', 'saasland-core'),
        'ti-hand-point-left' => esc_html__( 'Hand Point Left', 'saasland-core'),
        'ti-hand-point-down' => esc_html__( 'Hand Point Down', 'saasland-core'),
        'ti-gallery' => esc_html__( 'Gallery', 'saasland-core'),
        'ti-face-smile' => esc_html__( 'Face Smile', 'saasland-core'),
        'ti-face-sad' => esc_html__( 'Face Sad', 'saasland-core'),
        'ti-credit-card' => esc_html__( 'Credit Card', 'saasland-core'),
        'ti-control-skip-forward' => esc_html__( 'Control Skip Forward', 'saasland-core'),
        'ti-control-record' => esc_html__( 'Control Record', 'saasland-core'),
        'Control-eject' => esc_html__( 'Control Eject', 'saasland-core'),
        'ti-comments-smiley' => esc_html__( 'Comments Smiley', 'saasland-core'),
        'ti-brush-alt' => esc_html__( 'Brush Alt', 'saasland-core'),
        'ti-youtube' => esc_html__( 'Youtube', 'saasland-core'),
        'ti-vimeo' => esc_html__( 'Vimeo', 'saasland-core'),
        'ti-twitter' => esc_html__( 'Twitter', 'saasland-core'),
        'ti-time' => esc_html__( 'Time', 'saasland-core'),
        'ti-tumblr' => esc_html__( 'Tumblr', 'saasland-core'),
        'ti-skype' => esc_html__( 'Skype', 'saasland-core'),
        'ti-share' => esc_html__( 'Share', 'saasland-core'),
        'ti-share-alt' => esc_html__( 'Share Alt', 'saasland-core'),
        'ti-rocket' => esc_html__( 'Rocket', 'saasland-core'),
        'ti-pinterest' => esc_html__( 'Pinterest', 'saasland-core'),
        'ti-new-window' => esc_html__( 'New Window', 'saasland-core'),
        'ti-microsoft' => esc_html__( 'Microsoft', 'saasland-core'),
        'ti-list-ol' => esc_html__( 'List Ol', 'saasland-core'),
        'ti-linkedin' => esc_html__( 'Linkedin', 'saasland-core'),
        'ti-layout-sidebar-2' => esc_html__( 'Layout Sidebar-2', 'saasland-core'),
        'ti-layout-grid4-alt' => esc_html__( 'Layout Grid4 Alt', 'saasland-core'),
        'ti-layout-grid3-alt' => esc_html__( 'Layout Grid3 Alt', 'saasland-core'),
        'ti-layout-grid2-alt' => esc_html__( 'Layout Grid2 Alt', 'saasland-core'),
        'ti-layout-column4-alt' => esc_html__( 'Layout Column4 Alt', 'saasland-core'),
        'ti-layout-column3-alt' => esc_html__( 'Layout Column3 Alt', 'saasland-core'),
        'ti-layout-column2-alt' => esc_html__( 'Layout Column2 Alt', 'saasland-core'),
        'ti-instagram' => esc_html__( 'Instagram', 'saasland-core'),
        'ti-google' => esc_html__( 'Google', 'saasland-core'),
        'ti-github' => esc_html__( 'Github', 'saasland-core'),
        'ti-flickr' => esc_html__( 'Flickr', 'saasland-core'),
        'ti-facebook' => esc_html__( 'Facebook', 'saasland-core'),
        'ti-dropbox' => esc_html__( 'Dropbox', 'saasland-core'),
        'ti-dribbble' => esc_html__( 'Dribbble', 'saasland-core'),
        'ti-apple' => esc_html__( 'Apple', 'saasland-core'),
        'ti-android' => esc_html__( 'Android', 'saasland-core'),
        'ti-save' => esc_html__( 'Save', 'saasland-core'),
        'ti-save-alt' => esc_html__( 'Save Alt', 'saasland-core'),
        'ti-yahoo' => esc_html__( 'Yahoo', 'saasland-core'),
        'ti-wordpress' => esc_html__( 'Wordpress', 'saasland-core'),
        'ti-vimeo-alt' => esc_html__( 'Vimeo Alt', 'saasland-core'),
        'ti-twitter-alt' => esc_html__( 'Twitter Alt', 'saasland-core'),
        'ti-tumblr-alt' => esc_html__( 'Tumblr Alt', 'saasland-core'),
        'ti-trello' => esc_html__( 'Trello', 'saasland-core'),
        'ti-stack-overflow' => esc_html__( 'Stack Overflow', 'saasland-core'),
        'ti-soundcloud' => esc_html__( 'Soundcloud', 'saasland-core'),
        'ti-sharethis' => esc_html__( 'Sharethis', 'saasland-core'),
        'ti-sharethis-alt' => esc_html__( 'Sharethis Alt', 'saasland-core'),
        'ti-reddit' => esc_html__( 'Reddit', 'saasland-core'),
        'ti-pinterest-alt' => esc_html__( 'Pinterest Alt', 'saasland-core'),
        'ti-microsoft-alt' => esc_html__( 'Microsoft Alt', 'saasland-core'),
        'ti-linux' => esc_html__( 'Linux', 'saasland-core'),
        'ti-jsfiddle' => esc_html__( 'Jsfiddle', 'saasland-core'),
        'ti-joomla' => esc_html__( 'Joomla', 'saasland-core'),
        'ti-html5' => esc_html__( 'Html5', 'saasland-core'),
        'ti-flickr-alt' => esc_html__( 'Flickr Alt', 'saasland-core'),
        'ti-email' => esc_html__( 'Email', 'saasland-core'),
        'ti-drupal' => esc_html__( 'Drupal', 'saasland-core'),
        'ti-dropbox-alt' => esc_html__( 'Dropbox Alt', 'saasland-core'),
        'ti-css3' => esc_html__( 'Css3', 'saasland-core'),
        'ti-rss' => esc_html__( 'Rss', 'saasland-core'),
        'ti-rss-alt' => esc_html__( 'Rss-alt', 'saasland-core')
    ];
}

function saasland_include_themify_icons() {
    return array_keys(saasland_themify_icons());
}

function saasland_loard_icons () {
    $icons = [
        'lupuorrc' => esc_html__('Confetti', 'saasland-core'),
        'hrqwmuhr' => esc_html__('Thumb Down', 'saasland-core'),
        'wxnxiano' => esc_html__('Book', 'saasland-core'),
        'jaghjelc' => esc_html__('Pets', 'saasland-core'),
        'yalwfksd' => esc_html__('Medical Mask', 'saasland-core'),
        'jvucoldz' => esc_html__('Layers', 'saasland-core'),
        'iltqorsz' => esc_html__('Target', 'saasland-core'),
        'slkvcfos' => esc_html__('Basket Trolley', 'saasland-core'),
        'gqdnbnwt' => esc_html__('Growth Chart', 'saasland-core'),
        'imamsnbq' => esc_html__( 'Nodding Man', 'saasland-core' ),
        'zzcjjxew' => esc_html__( 'Location Pin', 'saasland-core' ),
        'msoeawqm' => esc_html__( 'Zoom', 'saasland-core' ),
        'rjzlnunf' => esc_html__( 'Heart', 'saasland-core' ),
        'nxaaasqe' => esc_html__( 'Arrows', 'saasland-core' ),
        'dxjqoygy' => esc_html__( 'Avatar', 'saasland-core' ),
        'mdgrhyca' => esc_html__( 'Star Rating', 'saasland-core' ),
        'eszyyflr' => esc_html__( 'Male Avatar', 'saasland-core' ),
        'gqzfzudq' => esc_html__( 'Globe', 'saasland-core' ),
        'wloilxuq' => esc_html__( 'Edit', 'saasland-core' ),
        'sbiheqdr' => esc_html__( 'Tool', 'saasland-core' ),
        'nkmsrxys' => esc_html__( 'Gift', 'saasland-core' ),
        'kbtmbyzy' => esc_html__( 'Clock', 'saasland-core' ),
        'qhgmphtg' => esc_html__( 'Computer', 'saasland-core' ),
        'rqqkvjqf' => esc_html__( 'Fingerprint', 'saasland-core' ),
        'nocovwne' => esc_html__( 'Document', 'saasland-core' ),
        'vixtkkbk' => esc_html__( 'Camera', 'saasland-core' ),
        'tdxypxgp' => esc_html__( 'Film', 'saasland-core' ),
        'gmzxduhd' => esc_html__( 'Home', 'saasland-core' ),
        'tyounuzx' => esc_html__( 'Eye', 'saasland-core' ),
        'zpxybbhl' => esc_html__( 'Consultation', 'saasland-core' ),
        'jfloqxvk' => esc_html__( 'Candle', 'saasland-core' ),
        'elzyzcar' => esc_html__( 'Candy cane', 'saasland-core' ),
        'efhpcbjj' => esc_html__( 'Christmas sock', 'saasland-core' ),
        'qccwedol' => esc_html__( 'Elf', 'saasland-core' ),
        'qduilmpq' => esc_html__( 'Firework', 'saasland-core' ),
        'wtzlmodt' => esc_html__( 'Holy Bible', 'saasland-core' ),
        'kdruzgxz' => esc_html__( 'Champagne flutes', 'saasland-core' ),
        'fxxbbjbc' => esc_html__( 'Santa', 'saasland-core' ),
        'qjvxqdov' => esc_html__( 'Star of Bethlehem', 'saasland-core' ),
        'ijznovhy' => esc_html__( '3D', 'saasland-core' ),
        'ngcezuqf' => esc_html__( 'Sphere', 'saasland-core' ),
        'tkgyrmwc' => esc_html__( 'Email', 'saasland-core' ),
        'mtdulhdc' => esc_html__( 'One key', 'saasland-core' ),
        'vcoyflbj' => esc_html__( 'Two key', 'saasland-core' ),
        'igpsgesd' => esc_html__( 'Three key', 'saasland-core' ),
        'wepqtdbh' => esc_html__( 'Birthday hat', 'saasland-core' ),
        'sgodrdhn' => esc_html__( 'Ferris wheel', 'saasland-core' ),
        'rulhujcg' => esc_html__( 'Duck', 'saasland-core' ),
        'mlmwskmm' => esc_html__( 'Woodpecker', 'saasland-core' ),
        'hpxruznz' => esc_html__( 'Wings', 'saasland-core' ),
        'xnfkhcfn' => esc_html__( 'Turkey', 'saasland-core' ),
        'bzqxpovj' => esc_html__( 'Bee', 'saasland-core' ),
        'byacrmae' => esc_html__( 'Horse', 'saasland-core' ),
        'ctmhjgcv' => esc_html__( 'Spider', 'saasland-core' ),
        'vqmupdxd' => esc_html__( 'Cat head', 'saasland-core' ),
        'twkviqpp' => esc_html__( 'Coral', 'saasland-core' ),
        'unqahzti' => esc_html__( 'Shark', 'saasland-core' ),
        'ilxelwgi' => esc_html__( 'Honeycombs', 'saasland-core' ),
        'uamufawi' => esc_html__( 'Bear', 'saasland-core' ),
        'cnhaewqi' => esc_html__( 'Squirrel', 'saasland-core' ),
        'jlkaerma' => esc_html__( 'Snake', 'saasland-core' ),
        'fgxmcqrv' => esc_html__( 'Maneki cat', 'saasland-core' ),
        'wzckbizc' => esc_html__( 'Paws', 'saasland-core' ),
        'yeallgsa' => esc_html__( 'Savings', 'saasland-core' ),
        'abdshgok' => esc_html__( 'Background 1', 'saasland-core' ),
        'yqbqexfk' => esc_html__( 'Background 2', 'saasland-core' ),
        'uvphnhwl' => esc_html__( 'Background 3', 'saasland-core' ),
        'osralwsf' => esc_html__( 'Background 4', 'saasland-core' ),
        'lfrnupjg' => esc_html__( 'Background 5', 'saasland-core' ),
        'rhbvmjsa' => esc_html__( 'Background 6', 'saasland-core' ),
        'dpwssiof' => esc_html__( 'Background 7', 'saasland-core' ),
        'gumgjepe' => esc_html__( 'Background 8', 'saasland-core' ),
        'bblxzszv' => esc_html__( 'Background 9', 'saasland-core' ),
        'agvffvdj' => esc_html__( 'Background 10', 'saasland-core' ),
        'mwfufvdv' => esc_html__( 'Background 11', 'saasland-core' ),
        'tadbtpcr' => esc_html__( 'Background 12', 'saasland-core' ),
        'nndmudsk' => esc_html__( 'Background 13', 'saasland-core' ),
        'cnmbpmsl' => esc_html__( 'Background 14', 'saasland-core' ),
        'qbeumxzm' => esc_html__( 'Background 15', 'saasland-core' ),
        'cvulazbb' => esc_html__( 'Background 16', 'saasland-core' ),
        'lkjyjeux' => esc_html__( 'Background 17', 'saasland-core' ),
        'fmcwhtnv' => esc_html__( 'Background 18', 'saasland-core' ),
        'ydcngaai' => esc_html__( 'Background 19', 'saasland-core' ),
        'flhaqqrd' => esc_html__( 'Background 20', 'saasland-core' ),
        'krmfspeu' => esc_html__( 'Arrows 2', 'saasland-core' ),
        'dzydjxom' => esc_html__( 'Arrow 1', 'saasland-core' ),
        'bgywtgwo' => esc_html__( 'Arrow 2', 'saasland-core' ),
        'gkditgni' => esc_html__( 'Arrow 3', 'saasland-core' ),
        'iiueiwdd' => esc_html__( 'Arrow 4', 'saasland-core' ),
        'wnkegycl' => esc_html__( 'Arrow 5', 'saasland-core' ),
        'rvuqcvqy' => esc_html__( 'Arrow 6', 'saasland-core' ),
        'qvzrpodt' => esc_html__( 'Arrow 7', 'saasland-core' ),
        'xgeyogar' => esc_html__( 'Arrow 8', 'saasland-core' ),
        'koyivthb' => esc_html__( 'Share', 'saasland-core' ),
        'udwhdpod' => esc_html__( 'Share 1', 'saasland-core' ),
        'rwotyanb' => esc_html__( 'Puzzle', 'saasland-core' ),
        'vieswnpa' => esc_html__( 'Music note', 'saasland-core' ),
        'rzrkjbrm' => esc_html__( 'Clipboard', 'saasland-core' ),
        'fgkmrslx' => esc_html__( 'Photo landscape', 'saasland-core' ),
        'jqyglkav' => esc_html__( 'Night sky', 'saasland-core' ),
        'tfosrbcn' => esc_html__( 'Shooting stars', 'saasland-core' ),
        'mmspidej' => esc_html__( 'Music album', 'saasland-core' ),
        'bgwzirmj' => esc_html__( 'Speakers', 'saasland-core' ),
        'soryfkft' => esc_html__( 'Echo speaker', 'saasland-core' ),
        'vnxmkidq' => esc_html__( 'Add song', 'saasland-core' ),
        'xqndcrvb' => esc_html__( 'Treble clef', 'saasland-core' ),
        'cnbtojmk' => esc_html__( 'Walkie-talkie', 'saasland-core' ),
        'fpipqhrr' => esc_html__( 'Microphone recording', 'saasland-core' ),
        'poblyvkl' => esc_html__( 'Food truck', 'saasland-core' ),
        'jntzsapy' => esc_html__( 'Police car', 'saasland-core' ),
        'uetqnvvg' => esc_html__( 'Truck', 'saasland-core' ),
        'mdksbrtj' => esc_html__( 'Ambulance', 'saasland-core' ),
        'ckuogwdx' => esc_html__( 'Electric car', 'saasland-core' ),
        'dnmrkoxw' => esc_html__( 'Airbag', 'saasland-core' ),
        'waumjsnp' => esc_html__( 'License plate', 'saasland-core' ),
        'mletffyr' => esc_html__( 'Windscreen', 'saasland-core' ),
        'wtxaetua' => esc_html__( 'Ferry', 'saasland-core' ),
        'bkzzedxx' => esc_html__( 'Sleepy driver', 'saasland-core' ),
        'rxtmmwvl' => esc_html__( 'Fetus', 'saasland-core' ),
        'cuvapfqt' => esc_html__( 'Feeding a baby', 'saasland-core' ),
        'suofjzof' => esc_html__( 'Embryo', 'saasland-core' ),
        'qecgidgl' => esc_html__( 'Baby bib', 'saasland-core' ),
        'bhbywgsm' => esc_html__( 'Shaving foam', 'saasland-core' ),
        'mekvzgwx' => esc_html__( 'Comb', 'saasland-core' ),
        'dqunxaob' => esc_html__( 'Spa flower', 'saasland-core' ),
        'wfroncyf' => esc_html__( 'Shampoo', 'saasland-core' ),
        'hpuklivk' => esc_html__( 'Sponge', 'saasland-core' ),
        'xbyoroeu' => esc_html__( 'Food resources', 'saasland-core' ),
        'bkgjmybn' => esc_html__( 'Electric teapot', 'saasland-core' ),
        'fpcjuvqt' => esc_html__( 'No alcohol', 'saasland-core' ),
        'ppnwdtgb' => esc_html__( 'Yerba mate', 'saasland-core' ),
        'szzsfswk' => esc_html__( 'Wine', 'saasland-core' ),
        'hzomhqxz' => esc_html__( 'Black tea', 'saasland-core' ),
        'vmhkxnfq' => esc_html__( 'Water', 'saasland-core' ),
        'uxtcmjmu' => esc_html__( 'Coffee machine', 'saasland-core' ),
        'oudlegmg' => esc_html__( 'Downtown', 'saasland-core' ),
        'jqnthkou' => esc_html__( 'City hall', 'saasland-core' ),
        'mfqgdxxm' => esc_html__( 'Mosque', 'saasland-core' ),
        'jtnbnevw' => esc_html__( 'Cathedral', 'saasland-core' ),
        'qgjxvqgb' => esc_html__( 'Pagoda', 'saasland-core' ),
        'ynxntkhy' => esc_html__( 'Orthodox church', 'saasland-core' ),
        'vxiujhli' => esc_html__( 'Aztec pyramid', 'saasland-core' ),
        'yttvpuhd' => esc_html__( 'Taj Mahal', 'saasland-core' ),
        'dlqgrmty' => esc_html__( 'Pyramids', 'saasland-core' ),
        'uixzulhh' => esc_html__( 'Ruins', 'saasland-core' ),
        'otlkfbpg' => esc_html__( 'Torii', 'saasland-core' ),
        'jjjmlddk' => esc_html__( 'Museum', 'saasland-core' ),
        'rlngnytn' => esc_html__( 'Church', 'saasland-core' ),
        'ajyyzcwv' => esc_html__( 'School', 'saasland-core' ),
        'tvyxmjyo' => esc_html__( 'Rules', 'saasland-core' ),
        'vlupvdhl' => esc_html__( 'IOTA', 'saasland-core' ),
        'fhtaantg' => esc_html__( 'Suitcase', 'saasland-core' ),
        'vaeagfzc' => esc_html__( 'Coin', 'saasland-core' ),
        'qhviklyi' => esc_html__( 'Coins', 'saasland-core' ),
        'gxulgxck' => esc_html__( 'Safety ring', 'saasland-core' ),
        'cmrzxpzz' => esc_html__( 'Free', 'saasland-core' ),
        'ssdupzsv' => esc_html__( 'Success', 'saasland-core' ),
        'zhxxdohn' => esc_html__( 'Free', 'saasland-core' ),
        'yyecuati' => esc_html__( 'Commodity', 'saasland-core' ),
        'rgyftmhc' => esc_html__( 'Dividends', 'saasland-core' ),
        'huwchbks' => esc_html__( 'Equity', 'saasland-core' ),
        'cjieiyzp' => esc_html__( 'Stock share', 'saasland-core' ),
        'uqpazftn' => esc_html__( 'Customers', 'saasland-core' ),
        'uukerzzv' => esc_html__( 'Demand', 'saasland-core' ),
        'yyecauzv' => esc_html__( 'Privacy policy', 'saasland-core' ),
        'soseozvi' => esc_html__( 'Video conference', 'saasland-core' ),
        'wwbetwxh' => esc_html__( 'Head lamp', 'saasland-core' ),
        'lrpzrvvn' => esc_html__( 'Rocking horse', 'saasland-core' ),
        'mhsepwkf' => esc_html__( 'Paper boat', 'saasland-core' ),
        'oohidvvw' => esc_html__( 'Flower doodle', 'saasland-core' ),
        'spxnqpau' => esc_html__( 'Monster', 'saasland-core' ),
        'owgzmwuj' => esc_html__( 'Tricycle', 'saasland-core' ),
        'mbcrjouw' => esc_html__( 'Wheelchair', 'saasland-core' ),
        'dqkyqxlp' => esc_html__( 'Old shop', 'saasland-core' ),
        'kekeoctr' => esc_html__( 'Automatic stairs', 'saasland-core' ),
        'ybgqhhgb' => esc_html__( 'Recycling', 'saasland-core' ),
        'lywgqtim' => esc_html__( 'Exit sign', 'saasland-core' ),
        'zpmqckup' => esc_html__( 'No entry', 'saasland-core' ),
        'vmppyudo' => esc_html__( 'Cinema', 'saasland-core' ),
        'kwbxfnke' => esc_html__( 'Fire hydrant', 'saasland-core' ),
        'yzadpakp' => esc_html__( 'Cemetery', 'saasland-core' ),
        'jpikaoyw' => esc_html__( 'Elections', 'saasland-core' ),
        'ryxufmfd' => esc_html__( 'Park bench', 'saasland-core' ),
        'mlnkdrif' => esc_html__( 'Bicycle', 'saasland-core' ),
        'ycnmpwon' => esc_html__( 'Pool', 'saasland-core' ),
        'mersmoqu' => esc_html__( 'Protest', 'saasland-core' ),
        'hovbgwmd' => esc_html__( 'Biking', 'saasland-core' ),
        'raayvuis' => esc_html__( 'Fireman', 'saasland-core' ),
        'qqtmmilg' => esc_html__( 'Electric scooter', 'saasland-core' ),
        'cvpqeffe' => esc_html__( 'Roadblock', 'saasland-core' ),
        'zbopvjaq' => esc_html__( 'Glasses', 'saasland-core' ),
        'tdrtiskw' => esc_html__( 'Error', 'saasland-core' ),
        'rhvddzym' => esc_html__( 'Send mail', 'saasland-core' ),
        'xqnbvely' => esc_html__( 'Quotation mark', 'saasland-core' ),
        'xhwleznj' => esc_html__( 'Enter key', 'saasland-core' ),
        'jxbsnyig' => esc_html__( 'USB cable', 'saasland-core' ),
        'qghrdngw' => esc_html__( 'Load balancer', 'saasland-core' ),
        'agkghzpc' => esc_html__( 'Micro sd card', 'saasland-core' ),
        'pndvzexs' => esc_html__( 'Computer mouse', 'saasland-core' ),
        'efzyjota' => esc_html__( 'Bluetooth', 'saasland-core' ),
        'wrprwmwt' => esc_html__( 'Server', 'saasland-core' ),
        'tclnsjgx' => esc_html__( 'Wireless connection', 'saasland-core' ),
        'igrslveu' => esc_html__( 'Pendrive', 'saasland-core' ),
        'hciqteio' => esc_html__( 'International music', 'saasland-core' ),
        'ibgjiwvi' => esc_html__( 'Greek helmet', 'saasland-core' ),
        'rqsvgwdj' => esc_html__( 'Archer', 'saasland-core' ),
        'apqkddqt' => esc_html__( 'Olympic rings', 'saasland-core' ),
        'rjteipmt' => esc_html__( 'Kimono', 'saasland-core' ),
        'pijqcxrg' => esc_html__( 'Aztec calendar', 'saasland-core' ),
        'lpfanbej' => esc_html__( 'African culture', 'saasland-core' ),
        'apbzdxqr' => esc_html__( 'Gong', 'saasland-core' ),
        'nsbufguq' => esc_html__( 'Da Vinci', 'saasland-core' ),
        'wvmphzds' => esc_html__( 'The Pope', 'saasland-core' ),
        'krcjnmyy' => esc_html__( 'Trumpet', 'saasland-core' ),
        'wcjauznf' => esc_html__( 'Cloud', 'saasland-core' ),
        'nlzvfogq' => esc_html__( 'Open box', 'saasland-core' ),
        'rbwzsktr' => esc_html__( 'Page view array', 'saasland-core' ),
        'gdjyhaga' => esc_html__( 'Page view column', 'saasland-core' ),
        'joeivjls' => esc_html__( 'Page view quilt', 'saasland-core' ),
        'eezceylz' => esc_html__( 'Paper waste', 'saasland-core' ),
        'ahatttod' => esc_html__( 'Circle', 'saasland-core' ),
        'hkqeuzpq' => esc_html__( 'Ellipse', 'saasland-core' ),
        'xmybtxmb' => esc_html__( 'Triangle', 'saasland-core' ),
        'tkuhvozl' => esc_html__( 'Rounded square', 'saasland-core' ),
        'baiwwlyi' => esc_html__( 'Rhombus', 'saasland-core' ),
        'kqxqomzp' => esc_html__( 'Polyline', 'saasland-core' ),
        'kfyekbgm' => esc_html__( 'Square', 'saasland-core' ),
        'vtgwital' => esc_html__( 'Rectangle', 'saasland-core' ),
        'ufknjsoh' => esc_html__( 'Polygon', 'saasland-core' ),
        'smeqxwcv' => esc_html__( 'Vlog camera', 'saasland-core' ),
        'ktxpktdd' => esc_html__( 'Joystick', 'saasland-core' ),
        'isvvzjbf' => esc_html__( 'Smart TV', 'saasland-core' ),
        'mbyiiqnh' => esc_html__( 'Alarm clock', 'saasland-core' ),
        'jqeuwnmb' => esc_html__( 'Ebook reader', 'saasland-core' ),
        'bxzmtpaz' => esc_html__( 'Skrews', 'saasland-core' ),
        'bccqzuyr' => esc_html__( 'Growing plant', 'saasland-core' ),
        'mottzqtt' => esc_html__( 'Greenhouse', 'saasland-core' ),
        'limsgwpx' => esc_html__( 'Iceberg', 'saasland-core' ),
        'xpyyoyss' => esc_html__( '1993-melting-glacier-global-warming-outline', 'saasland-core' ),
        'emjmorqk' => esc_html__( 'Solar panel', 'saasland-core' ),
        'qrbokoyz' => esc_html__( 'Sale', 'saasland-core' ),
        'itmmouju' => esc_html__( 'Grocery shelf', 'saasland-core' ),
        'dnoiydox' => esc_html__( 'Basket', 'saasland-core' ),
        'wjwuvtno' => esc_html__( 'Link & unlink', 'saasland-core' ),
        'gsqxdxog' => esc_html__( 'Bin', 'saasland-core' ),
        'puvaffet' => esc_html__( 'Edit document', 'saasland-core' ),
        'mecwbjnp' => esc_html__( 'Plus circle', 'saasland-core' ),
        'rivoakkk' => esc_html__( 'Minus circle', 'saasland-core' ),
        'oswatybr' => esc_html__( 'Lab bottle', 'saasland-core' ),
        'nobciafz' => esc_html__( 'IT developer', 'saasland-core' ),
        'ntformof' => esc_html__( 'Reggae music', 'saasland-core' ),
        'sodlceyy' => esc_html__( 'Nodding woman', 'saasland-core' ),
        'pithnlch' => esc_html__( 'Smile emoji', 'saasland-core' ),
        'dzllstvg' => esc_html__( 'Wow emoji', 'saasland-core' ),
        'bwnhdkha' => esc_html__( 'Female Avatar', 'saasland-core' ),
        'apuwlldu' => esc_html__( 'Disco ball', 'saasland-core' ),
        'rcopausw' => esc_html__( 'Applause', 'saasland-core' ),
        'twhnrqim' => esc_html__( 'Hookah', 'saasland-core' ),
        'qoozyitg' => esc_html__( 'Rugby ball', 'saasland-core' ),
        'ycjlxmbw' => esc_html__( 'Housekeeper', 'saasland-core' ),
        'bbnkwdur' => esc_html__( 'Folder', 'saasland-core' ),
        'jpdtnwas' => esc_html__( 'Pizza', 'saasland-core' ),
        'wfkxiwtw' => esc_html__( 'Morale', 'saasland-core' ),
        'xvkrsjya' => esc_html__( 'Knife', 'saasland-core' ),
        'fyhanzjw' => esc_html__( 'Vegetable bag', 'saasland-core' ),
        'stbcbpfl' => esc_html__( 'Apple', 'saasland-core' ),
        'eqwebkyi' => esc_html__( 'Three-leaf clover', 'saasland-core' ),
        'xsqzqbax' => esc_html__( 'Horseshoe', 'saasland-core' ),
        'bhcvxmsz' => esc_html__( 'Dandelion', 'saasland-core' ),
        'cmwbcztt' => esc_html__( 'Sunflower', 'saasland-core' ),
        'pxfpxfyp' => esc_html__( 'Rose', 'saasland-core' ),
        'paspbkiv' => esc_html__( 'Palm tree', 'saasland-core' ),
        'ijtstpbh' => esc_html__( 'Telephone call', 'saasland-core' ),
        'akqpsmch' => esc_html__( 'Hand washing', 'saasland-core' ),
        'xgpppfia' => esc_html__( 'Hand washing 2', 'saasland-core' ),
        'toojndol' => esc_html__( 'Hand washing 3', 'saasland-core' ),
        'fgfuaarl' => esc_html__( 'Hand washing 4', 'saasland-core' ),
        'uaewpgup' => esc_html__( 'Hand washing 5', 'saasland-core' ),
        'javxropk' => esc_html__( 'Hand washing 6', 'saasland-core' ),
        'mvstncei' => esc_html__( 'Hand washing 7', 'saasland-core' ),
        'ugoqjomi' => esc_html__( 'Hand washing 8', 'saasland-core' ),
        'qnxmsqym' => esc_html__( 'Hand washing 9', 'saasland-core' ),
        'aaodnvls' => esc_html__( 'Hand washing 10', 'saasland-core' ),
        'frgdfrqb' => esc_html__( 'Hand washing 11', 'saasland-core' ),
        'gazjnoea' => esc_html__( 'Hand washing 12', 'saasland-core' ),
        'owpijlcy' => esc_html__( 'Cough', 'saasland-core' ),
        'mypzgycw' => esc_html__( 'Fever', 'saasland-core' ),
        'ixlgmsii' => esc_html__( 'Antibacterial spray', 'saasland-core' ),
        'hsotfjpx' => esc_html__( 'injection', 'saasland-core' ),
        'ippkhukl' => esc_html__( 'Walk', 'saasland-core' ),
        'hbjlznlo' => esc_html__( 'Test tubes', 'saasland-core' ),
        'hdiorcun' => esc_html__( 'Heartbeat', 'saasland-core' ),
        'vsoxntbh' => esc_html__( 'Sofa', 'saasland-core' ),
        'qdmapxxp' => esc_html__( 'Sink', 'saasland-core' ),
        'dbsklakl' => esc_html__( 'Chandelier', 'saasland-core' ),
        'yrvfcoqx' => esc_html__( 'Lava lamp', 'saasland-core' ),
        'awzatcif' => esc_html__( 'Ladder', 'saasland-core' ),
        'ghiijzmu' => esc_html__( 'Potted flower plant', 'saasland-core' ),
        'iyqamhwd' => esc_html__( 'Cargo ship', 'saasland-core' ),
        'xawkzoxm' => esc_html__( 'Wooden box', 'saasland-core' ),
        'lthhecik' => esc_html__( 'Trolley', 'saasland-core' ),
        'mgmymbso' => esc_html__( 'Scuba tank', 'saasland-core' ),
        'xxbnviyf' => esc_html__( 'Wharf', 'saasland-core' ),
        'ymrqtsej' => esc_html__( 'Loader', 'saasland-core' ),
        'ulhdumaq' => esc_html__( 'Loader 1', 'saasland-core' ),
        'dpinvufc' => esc_html__( 'Loader 2', 'saasland-core' ),
        'kvsszuvz' => esc_html__( 'Loader 3', 'saasland-core' ),
        'xjovhxra' => esc_html__( 'Loader 4', 'saasland-core' ),
        'dtgezzsi' => esc_html__( 'Multimedia code', 'saasland-core' ),
        'qhzuzhnx' => esc_html__( 'Djembe drum', 'saasland-core' ),
        'ihiyrlio' => esc_html__( 'Desertification', 'saasland-core' ),
        'oyclgnwc' => esc_html__( 'Water drop', 'saasland-core' ),
        'yzctygpq' => esc_html__( 'Wifi', 'saasland-core' ),
        'ouvpilty' => esc_html__( 'Pushups', 'saasland-core' ),
        'lxlstztz' => esc_html__( 'Ski simulator', 'saasland-core' ),
        'mqlsefjv' => esc_html__( 'Skateboarding', 'saasland-core' ),
        'kyvwwsnj' => esc_html__( 'Plank', 'saasland-core' ),
        'ribdawhq' => esc_html__( 'Herbs', 'saasland-core' ),
        'hfmxsefj' => esc_html__( 'Php code', 'saasland-core' ),
        'rhvlcscg' => esc_html__( 'Json', 'saasland-core' ),
        'buqfvmsj' => esc_html__( 'Html5 code', 'saasland-core' ),
        'bkqtuigh' => esc_html__( 'Python code', 'saasland-core' ),
        'kkwzhxjj' => esc_html__( 'Java code', 'saasland-core' ),
        'ptbbcteb' => esc_html__( 'C++ code', 'saasland-core' ),
        'ybfcwnqv' => esc_html__( 'Code fork', 'saasland-core' ),
        'anihkfxp' => esc_html__( 'Command window', 'saasland-core' ),
        'elvincae' => esc_html__( 'Api', 'saasland-core' ),
        'xxtkutpo' => esc_html__( 'Rest API', 'saasland-core' ),
        'ochimkct' => esc_html__( 'Repository', 'saasland-core' ),
        'fqrjldna' => esc_html__( 'QR code', 'saasland-core' ),
        'rjkghepa' => esc_html__( 'No beverages', 'saasland-core' ),
        'xwjtkymn' => esc_html__( 'Scroll down', 'saasland-core' ),
        'wtfdpwey' => esc_html__( 'Scroll down', 'saasland-core' ),
        'uuxlmlza' => esc_html__( 'First place', 'saasland-core' ),
        'bqvgsxxi' => esc_html__( 'Swimmer cap', 'saasland-core' ),
        'ukwpspxw' => esc_html__( 'Boxing glove', 'saasland-core' ),
        'wgwcqouc' => esc_html__( 'Menu', 'saasland-core' ),
        'bwhjesak' => esc_html__( 'Menu 1', 'saasland-core' ),
        'phtfmmnb' => esc_html__( 'Menu 2', 'saasland-core' ),
        'uzrqzyei' => esc_html__( 'Menu 3', 'saasland-core' ),
        'jtqpkhoh' => esc_html__( 'Menu 4', 'saasland-core' ),
        'ytgufzvb' => esc_html__( 'Radio button', 'saasland-core' ),
        'urhcgqxz' => esc_html__( 'Web analytics', 'saasland-core' ),
        'cpbmxdpb' => esc_html__( 'Vector design', 'saasland-core' ),
        'dizvjgip' => esc_html__( 'Bulb', 'saasland-core' ),
    ];

    return $icons;

}

function saasland_loard_icons_get_attr ($arr = [], $sep="," ) {

    if(empty($arr)) {
        return $arr;
    }
    $get_color = implode($sep , array_map(
        function ($v, $k) { return sprintf("%s:%s",$k, $v); },
        $arr,
        array_keys($arr)
    ));
 return $get_color;
}
